services:
  frontend:
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    restart: always
    depends_on:
      - backend
  backend:
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=mongodb+srv://dbUser:FFHlff5050filqqu@cluster0.ifdjskt.mongodb.net/DeviceSavings_DB?retryWrites=true&w=majority